name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish Packages/UnityFx.Outline
      - run: npm publish Packages/UnityFx.Outline.PostProcessing
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm publish Packages/UnityFx.Outline
      - run: npm publish Packages/UnityFx.Outline.PostProcessing
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
